### PR TITLE
Adding WordPress E-books

### PR DESCRIPTION
**Pull request by samuelguebo**
* WordPress 3 Plugin Development Essentials
* WordPress 3.0 jQuery
* WordPress for Web Developers
* WordPress Theme Development, 3rd Edition

### CODE REVIEW

**Review by xSavitar — COMMENTED** [review]
I think this PR is okay! @rosalieper will review and I will merge. Thanks @samuelguebo.

**Review by xSavitar — APPROVED** [review]
@rosalieper is delaying to merge. Doing it myself.

**Comment by xSavitar** [comment]
Thanks for the PR @samuelguebo.

**Comment by rosalieper** [comment]
Thanks for the PR @samuelguebo, sorry for the delay @ch3nkula

**Comment by samuelguebo** [comment]
You're welcome @ch3nkula and @rosalieper. Looking forward to collaborating more.

**Pull request merged**
